workflows:
  android-build:
    name: Android Build
    max_build_duration: 120
    environment:
      vars:
        ANDROID_HOME: /opt/android-sdk-linux
    scripts:
      # Upgrade pip
      - python3 -m pip install --upgrade pip
      # Install Python packages needed for Kivy + Buildozer
      - python3 -m pip install kivy openpyxl cython buildozer
      # Check Buildozer version
      - python3 -m buildozer --version
      # Build APK
      - python3 -m buildozer android debug
    artifacts:
      - bin/*.apk